version: "3.9"
services:
  app:
    build: .
    container_name: app
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    env_file:
     - .env.dev
    depends_on:
     - db
     
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
     - "5432:5432"
     
volumes:
    postgres_data: